# REST Client
GET http://localhost:3001/employee/personnel
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY3NjkxNTk2Nn0.qcsvuEuSzrZBh4bnOBT7t6dGvwyqEyLqoMj67a2gpZI
###
POST http://localhost:3001/employee/token
Content-Type: application/json

{
	"username": "admin",
	"password": "password"
}
